package com.example.simon.ballapp;

import android.content.Context;
import android.content.res.Resources;
import android.graphics.BitmapFactory;
import android.util.DisplayMetrics;

import java.util.Random;

public class Powerup extends GameObject
{
    // Enum to describe type of powerup, mostly for code readability
    public enum Type
    {
        EXTRABALL, LARGERPADDLE, SPEEDBOOST, PIERCING
    }

    // Fields
    DisplayMetrics metrics;
    int scrWidth, scrHeight;
    float speedY, speedX;
    float radius;
    Random rnd = new Random();

    public Type getPowerType()
    {
        return powerType;
    }

    private Type powerType;

    public Powerup(Context context, float left, float top, float right, float bottom, int id)
    {
        super(context, left, top, right, bottom, id);

        // Get metrics of display
        metrics = Resources.getSystem().getDisplayMetrics();
        scrHeight = metrics.heightPixels;
        scrWidth = metrics.widthPixels;
        // Set falling speed of powerup
        speedY = 10;

        radius = objRect.right - objRect.left;

        // Randomly created a type of powerup
        switch (rnd.nextInt(4))
        {
            // If the random number is 0
            case 0:
                powerType = Type.PIERCING; // Set type to PIERCING
                id = R.drawable.powerupyellow; // Set the id (used to the bitmap) to yellow
                break;
            case 1: // Same logic as above but with different values assigned
                powerType = Type.EXTRABALL;
                id = R.drawable.powerupgreen;
                break;
            case 2:
                powerType = Type.SPEEDBOOST;
                id = R.drawable.powerupred;
                break;
            case 3:
                powerType = Type.LARGERPADDLE;
                id = R.drawable.powerupblue;
                break;
        }

        // Set the bitmap to the id generated by the random number
        setResizedBitmap(this, BitmapFactory.decodeResource(context.getResources(), id));
    }


    @Override
    public void update()
    {
        super.update();

        // Move the powerup
        Move();

        // If the powerup reaches below the screen
        if (objRect.top > GameWorld.getScreenY())
        {
            // Remove the powerup from the game
            GameWorld.getGameObjects().remove(this);
        }
    }

    // Move the powerup
    public void Move()
    {
        // Add speedY to Rect top & bottom
        objRect.top += speedY;
        objRect.bottom += speedY;
    }

    @Override
    void onCollision(GameObject other)
    {

    }
}
